--- # this is  my first yml
- hosts: demo
  become: yes
  tasks:
    - name: installing appche in centos machine
      yum: pkg=httpd state=present
      async: 3
      poll: 1
      notify: start apache
    - name: run a command directory
      command: echo hi-Mukesh
      register: output
    - debug: var=output.stdout    
  handlers:
    - name: start apache
      service: name=httpd state=started
    
