--- # this is  my first yml
- hosts: all
  become: yes
  tasks:
    - name: installing appche in centos machine
      yum: pkg=httpd state=present
      when: ansible_os_family == "RedHat"
    - name: installing appche ubuntu
      apt: pkg=apache2 state=present
      when: ansible_os_family == "Debian"
    - name: start apache
      service: name=httpd state=started
      when: ansible_os_family == "RedHat" 
    - name: start apche on master
      service: name=apache2 state=started
      when: ansible_os_family == "Debian"
